/* Developer-facing world content studio. All writes use the reviewed catalog editor. */
window.GameDebug = function(api) {
  const node=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n;};
  const icons={quests:'\u2726',enemies:'\u2620',enemy_abilities:'\u2194',enemy_weapons:'\u2694',weapon_types:'\u2021',weapon_definitions:'\u2694',gear_definitions:'\u25c8',abilities:'\u2736',afflictions:'\u2623',entity_types:'\u25a3',consumables:'\u25c9',essences:'\u25c6',orb_outcomes:'\u2727',villages:'\u2302',shops:'\u25c7',shop_tables:'\u2637',ranks:'\u265c',rest_policies:'\u263e',loot_types:'\u25c8'};
  const root=node('section','dev-studio');
  root.innerHTML=`<style>
  .dev-studio{--ink:#e9edf4;--sub:#8e97a6;--edge:#28303c;--card:#171c24;--deep:#10141a;--gold:#d2a958;padding:0!important;color:var(--ink)}
  .studio-shell{height:calc(100dvh - 132px);min-height:0;background:var(--deep);border:1px solid var(--edge);display:grid;grid-template-columns:clamp(210px,12vw,260px) minmax(0,1fr);overflow:hidden}.studio-side{background:#13171d;border-right:1px solid var(--edge);padding:22px 14px;display:flex;flex-direction:column}.studio-brand{padding:0 10px 22px;border-bottom:1px solid var(--edge)}.studio-brand b{display:block;font:600 17px Georgia,serif;letter-spacing:.04em}.studio-brand small{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--gold)}
  .studio-nav{display:grid;gap:4px;padding-top:18px;min-height:0;flex:1;align-content:start;overflow-y:auto}.studio-nav button{display:flex;align-items:center;gap:11px;text-align:left;background:transparent!important;color:var(--sub)!important;border:0;border-radius:3px;padding:11px 12px;font-size:13px}.studio-nav button:hover{color:var(--ink)!important;transform:none}.studio-nav button[aria-current=true]{color:var(--ink)!important;background:#242a33!important;box-shadow:inset 2px 0 var(--gold)}.studio-nav i{width:19px;text-align:center;color:var(--gold);font-style:normal}.studio-side-note{margin-top:auto;padding:16px 10px 0;border-top:1px solid var(--edge);font-size:11px;color:var(--sub)}.studio-live{display:flex;align-items:center;gap:7px;color:#85b88f;margin-bottom:4px}.studio-live:before{content:'';width:6px;height:6px;border-radius:50%;background:#72b47e;box-shadow:0 0 8px #72b47e}
  .studio-main{min-width:0;min-height:0;display:flex;flex-direction:column}.studio-top{min-height:66px;padding:13px 24px;border-bottom:1px solid var(--edge);display:flex;align-items:center;gap:14px}.studio-search{position:relative;flex:1}.studio-search:before{content:'\u2315';position:absolute;left:13px;top:7px;color:var(--sub)}.studio-search input{width:100%;padding:9px 12px 9px 38px;border-radius:3px;background:#181d25}.studio-button{border-radius:3px;background:var(--gold);color:#17130b;padding:9px 14px;font-size:12px}.studio-button.secondary{background:transparent;color:var(--sub);border-color:var(--edge)}.studio-content{padding:28px;min-height:0;flex:1;display:flex;flex-direction:column;overflow:hidden}.studio-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:25px}.studio-kicker{text-transform:uppercase;letter-spacing:.17em;color:var(--gold);font-size:10px;margin:0 0 6px}.studio-heading h2{font:500 30px/1.1 Georgia,serif;margin:0}.studio-heading p{font-size:12px;color:var(--sub);margin:7px 0 0}.studio-actions{display:flex;gap:8px}
  .studio-stats{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--edge);margin-bottom:22px}.studio-stat{padding:14px 17px;border-right:1px solid var(--edge)}.studio-stat:last-child{border:0}.studio-stat small{display:block;text-transform:uppercase;letter-spacing:.1em;font-size:9px;color:var(--sub)}.studio-stat strong{font:500 22px Georgia,serif}.studio-stat span{font-size:10px;color:#7fb389;margin-left:6px}.studio-panel{border:1px solid var(--edge);background:var(--card);min-height:0;display:flex;flex-direction:column}.studio-panel-head{padding:14px 17px;border-bottom:1px solid var(--edge);display:flex;justify-content:space-between;gap:12px;align-items:center;flex:0 0 auto}.studio-panel-head b{font-size:12px;text-transform:uppercase;letter-spacing:.08em}.studio-count{font-size:10px;color:var(--sub)}.studio-list{display:grid;min-height:0;flex:1;overflow-y:auto;overscroll-behavior-y:contain;scrollbar-gutter:stable}.studio-row{display:grid;grid-template-columns:minmax(180px,1.5fr) minmax(95px,.7fr) minmax(120px,1fr) auto;gap:18px;align-items:center;padding:15px 17px;border-bottom:1px solid var(--edge);cursor:pointer}.studio-row:last-child{border:0}.studio-row:hover,.studio-row.selected{background:#1d232c}.studio-row.selected{box-shadow:inset 2px 0 var(--gold)}.studio-row h3{font:500 15px Georgia,serif;margin:0 0 3px}.studio-row p,.studio-row small{margin:0;color:var(--sub);font-size:10px}.studio-tag{justify-self:start;border:1px solid #46505e;padding:3px 7px;color:#b7c0cd!important;text-transform:uppercase;letter-spacing:.07em}.studio-row button{background:transparent;color:var(--sub);border:0;padding:6px;font-size:18px}
  .studio-browser{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(300px,.8fr);gap:18px;align-items:stretch;min-height:0;flex:1}.studio-detail{border:1px solid var(--edge);background:var(--card);padding:20px;min-height:0;max-height:100%;overflow-y:auto;overscroll-behavior-y:contain}.studio-detail-head{display:flex;justify-content:space-between;gap:12px}.studio-detail h3{font:500 22px Georgia,serif;margin:0}.studio-detail h4{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:var(--gold);margin:22px 0 9px}.studio-detail p{font-size:12px;color:var(--sub)}.studio-chips{display:flex;flex-wrap:wrap;gap:7px}.studio-chip{font-size:11px;border:1px solid var(--edge);padding:5px 8px;color:#c2cad5}.studio-chip.link{background:transparent;border-radius:3px;font-weight:400}.studio-empty{padding:48px;text-align:center;color:var(--sub)}.studio-warning{color:#dfa39d!important}.studio-json{white-space:pre-wrap;overflow-wrap:anywhere;background:#10141a;padding:12px;font-size:11px;color:#aeb9c9;max-height:260px;overflow:auto}
  @media(min-width:1700px){.studio-browser{grid-template-columns:minmax(0,1.45fr) minmax(380px,.7fr);gap:24px}.studio-content{padding:34px}}@media(max-width:900px){.studio-browser{grid-template-columns:1fr}.studio-detail{position:static}}@media(max-width:760px){.studio-shell{height:calc(100dvh - 150px);grid-template-columns:1fr}.studio-side{border:0;border-bottom:1px solid var(--edge);padding:14px}.studio-brand,.studio-side-note{display:none}.studio-nav{display:flex;overflow:auto;padding:0}.studio-nav button{flex:0 0 auto}.studio-content{padding:19px 14px}.studio-heading{align-items:flex-start;flex-direction:column}.studio-stats{grid-template-columns:1fr 1fr}.studio-stat:nth-child(2){border-right:0}.studio-stat:nth-child(-n+2){border-bottom:1px solid var(--edge)}.studio-row{grid-template-columns:1fr auto}.studio-row>*:nth-child(2),.studio-row>*:nth-child(3){display:none}.studio-top{padding:10px 14px}}
  </style>`;
  const shell=node('div','studio-shell'),side=node('aside','studio-side'),main=node('div','studio-main');root.append(shell);shell.append(side,main);
  side.innerHTML='<div class="studio-brand"><small>Mosswood</small><b>Worldsmith</b></div>';
  const nav=node('nav','studio-nav'),sideNote=node('div','studio-side-note');sideNote.innerHTML='<div class="studio-live">Development realm</div><div>Changes are validated before publish.</div>';side.append(nav,sideNote);
  const top=node('div','studio-top'),searchWrap=node('div','studio-search'),search=node('input');search.type='search';search.placeholder='Search world content...';search.setAttribute('aria-label','Search world content');searchWrap.append(search);
  const refresh=node('button','studio-button secondary','Refresh'),exportButton=node('button','studio-button secondary','Export');top.append(searchWrap,refresh,exportButton);main.append(top);const content=node('div','studio-content');main.append(content);
  const sections=[{key:'quests',label:'Quests',singular:'quest',copy:'Draft routes, village regions, encounter groups, rewards, and weighted loot tables.'},{key:'enemies',label:'Enemies',singular:'enemy',copy:'Create enemy archetypes and inspect every assigned ability and weapon.'},{key:'enemy_abilities',label:'Enemy abilities',singular:'enemy ability assignment',copy:'Associate enemies with abilities and tune selection weight and priority.'},{key:'enemy_weapons',label:'Enemy weapons',singular:'enemy weapon assignment',copy:'Associate each enemy with a weapon type.'},{key:'abilities',label:'Abilities',singular:'ability',copy:'Create combat abilities and inspect enemy and essence recipe associations.'},{key:'afflictions',label:'Afflictions',singular:'affliction',copy:'Define status effects and inspect the abilities that apply them.'},{key:'entity_types',label:'Enemy types',singular:'enemy type',copy:'Define enemy categories and their affliction resistances.'},{key:'essences',label:'Essences',singular:'essence',copy:'Define essence items and inspect the orb recipes that unlock their abilities.'},{key:'orb_outcomes',label:'Essence recipes',singular:'essence recipe',copy:'Associate an orb and essence combination with the ability it teaches.'},{key:'consumables',label:'Loot items',singular:'loot item',copy:'Create consumables, essences, and orbs that can appear in quest loot tables.'},{key:'weapon_types',label:'Weapon types',singular:'weapon type',copy:'Define weapon families and inspect blueprints, enemies, and loot using them.'},{key:'weapon_definitions',label:'Weapons',singular:'weapon',copy:'Create weapon blueprints and inspect their quest loot availability.'},{key:'gear_definitions',label:'Armor',singular:'armor piece',copy:'Create equippable armor, rank requirements, bonuses, and prices.'},{key:'ranks',label:'Ranks',singular:'rank',copy:'Curate progression gates and inspect rank requirements across content.'},{key:'rest_policies',label:'Rest policies',singular:'rest policy',copy:'Define recovery rules used by quests and the village.'},{key:'loot_types',label:'Loot types',singular:'loot type',copy:'Curate the stable categories used to describe rewards.'},{key:'villages',label:'Villages',singular:'village',copy:'Inspect regions, connected quest routes, shops, and stock tables.'},{key:'shops',label:'Shops',singular:'shop',copy:'Associate shops with villages and curate their departments.'},{key:'shop_tables',label:'Shop tables',singular:'shop table',copy:'Associate stock tables with shops and curate the items they sell.'}];
  sections.splice(sections.findIndex(s=>s.key==='abilities')+1,0,{key:'ability_archetypes',label:'Ability archetypes',singular:'archetype',copy:'Create reusable starting points with editable dials, follow-up effects, and rank upgrades.'});
  icons.ability_archetypes='\u2736';
  let data=null,current='quests',selected=null,renderedSection=null;
  const libraryScroll={};
  const editDefinition=GameCatalogEditor(api,async()=>{await load('Saved successfully.');});
  const schema=()=>data?.editor?.catalogs?.[current];
  const catalogRecords=name=>data?.editor?.catalogs?.[name]?.records||[];
  const abilityName=id=>catalogRecords('abilities').find(r=>String(r.values.id)===String(id))?.values.name||id;
  function category(record){const v=record.values;if(current==='ability_archetypes')return v.definition?.effect_type||'template';if(current==='quests')return v.region;if(current==='enemies')return v.enemy_type;if(['enemy_abilities','enemy_weapons'].includes(current))return 'assignment';if(current==='abilities')return v.effect_type;if(current==='afflictions')return v.rules?.harmful===false?'beneficial':'harmful';if(current==='entity_types')return 'enemy type';if(current==='essences')return v.active?'active':'retired';if(current==='orb_outcomes')return 'recipe';if(current==='consumables')return v.effect;if(current==='weapon_types')return 'weapon family';if(current==='gear_definitions')return v.slot;if(current==='ranks')return `level ${v.min_level}`;if(current==='rest_policies')return 'recovery';if(current==='loot_types')return 'loot';if(current==='villages')return v.region;if(current==='shops')return v.village_slug;if(current==='shop_tables')return v.category;return v.weapon_type_slug||'definition';}
  const recordLabel=(catalog,record)=>record?.values.name||record?.values.slug||record?.values.consumable_slug||record?.values.enemy_slug||record?.values.shop_slug||Object.values(record?.key||{}).join(' + ');
  function relationLink(catalog,record,label){const button=node('button','studio-chip link',label||recordLabel(catalog,record));button.type='button';button.onclick=()=>{current=catalog;selected=record;search.value='';render();};return button;}
  function relationGroup(box,title,links,empty='None assigned.'){box.append(node('h4','',title));const chips=node('div','studio-chips');if(links.length)chips.append(...links);else chips.append(node('span','studio-chip',empty));box.append(chips);}
  const questDrops=quest=>(quest.values.journey?.encounter_groups?.loot_tiers||[]).flatMap(tier=>(tier.drops||[]).map(drop=>({tier,drop})));
  function readonlyRows(){
    if(!data)return [];
    if(current==='quests')return (data.quests||[]).map(v=>({key:{slug:v.slug},values:v,revision:null}));
    if(current==='enemies')return (data.enemies||[]).map(v=>({key:{slug:v.slug},values:v,revision:null}));
    if(['abilities','villages','shops','shop_tables'].includes(current))return (data[current]||[]).map(v=>({key:{id:v.id||v.slug},values:v,revision:null,readonly:true}));
    if(current==='weapon_definitions'){
      const seen=new Map();
      for(const quest of data.quests||[])for(const tier of quest.journey?.loot_tables||[])for(const item of tier.items||[]){
        if(!item.weapon_type||item.base_damage==null)continue;
        const slug=`${quest.slug}-${item.name}`.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
        if(!seen.has(slug))seen.set(slug,{slug,name:item.name,weapon_type_slug:item.weapon_type,base_damage:item.base_damage,required_rank:'iron',source_quest:quest.name});
      }
      return [...seen.values()].map(v=>({key:{slug:v.slug},values:v,revision:null,readonly:true}));
    }
    return [];
  }
  const sourceRows=()=>{const records=schema()?.records;if(records?.length)return records;return readonlyRows();};
  function summary(record){const v=record.values;if(current==='ability_archetypes')return `${v.definition?.effect_type||'custom'} · ${(v.definition?.effect_chain||[]).length} follow-ups`;if(current==='quests')return `${v.region} \u00b7 difficulty ${v.difficulty} \u00b7 ${(v.journey?.stages||[]).length} stages`;if(current==='enemies')return `${v.enemy_type} \u00b7 ${Object.keys(v.attributes||{}).length} attributes`;if(current==='enemy_abilities')return `${v.enemy_slug} \u2192 ${abilityName(v.ability_id)} \u00b7 weight ${v.weight}`;if(current==='enemy_weapons')return `${v.enemy_slug} \u2192 ${v.weapon_type_slug}`;if(current==='weapon_types')return `${(v.tags||[]).join(', ')||'no tags'}`;if(current==='weapon_definitions')return `${v.weapon_type_slug} \u00b7 ${v.base_damage} damage \u00b7 ${v.required_rank} rank`;if(current==='abilities')return `${v.effect_type||'effect'} \u00b7 power ${v.power??'\u2014'}`;if(current==='afflictions')return `${v.damage} damage \u00b7 ${v.duration} rounds \u00b7 ${v.max_stacks} stacks`;if(current==='entity_types')return `${Object.keys(v.status_resistances||{}).length} resistances`;if(current==='essences')return `${v.active?'active':'retired'} \u00b7 ${Object.keys(v.powers||{}).length} powers`;if(current==='orb_outcomes')return `${v.essence_slug} + ${v.orb_slug} \u2192 ${abilityName(v.ability_id)}`;if(current==='consumables')return `${v.effect} \u00b7 power ${v.power}`;if(current==='ranks')return `level ${v.min_level} \u00b7 ${v.ability_slots} ability slots`;if(current==='rest_policies')return `${v.settings?.heal_percent??0}% healing`;if(current==='loot_types')return v.name;if(current==='villages')return v.region;if(current==='shops')return `${v.village_slug} \u00b7 shop`;if(current==='shop_tables')return `${v.shop_slug} \u00b7 ${v.category} \u00b7 ${(v.items||[]).length} items`;return `${v.slot} \u00b7 ${v.required_rank} rank \u00b7 ${v.price} gold`;}
  function rows(){const q=search.value.trim().toLowerCase();return sourceRows().filter(r=>JSON.stringify(r.values).toLowerCase().includes(q));}
  function open(record,copy=false){if(record.readonly||!data.editor?.can_edit||!schema())return;editDefinition(current,record,schema(),data.editor.catalogs,copy);}
  function createAssociation(catalog,values){const target=data.editor?.catalogs?.[catalog];if(!data.editor?.can_edit||!target)return;editDefinition(catalog,{key:{},values,revision:null},target,data.editor.catalogs,true);}
  function detailAction(label,action){const b=node('button','studio-button secondary',label);b.type='button';b.onclick=action;return b;}
  async function removeAssociation(record){if(!confirm('Remove this association? Existing encounter snapshots will not change.'))return;try{await api('/catalog-editor',{catalog:current,key:record.key,values:record.values,expected_revision:record.revision,remove:true});await load('Association removed.');}catch(e){sideNote.querySelector('div:last-child').textContent=e.message;}}
  function createDefinition(){
    if(!data.editor?.can_edit){const warning=node('p','studio-warning','Creating content is disabled for this account. A developer account is required.');content.prepend(warning);return;}
    const first=(catalog,filter=()=>true)=>data.editor.catalogs[catalog]?.records.find(r=>filter(r.values))?.values;
    const templates={
      abilities:{...(first('abilities')||{}),id:'',slug:'new-ability',name:'New Ability',description:'',archetype_slug:null,effect_type:'damage',target_type:'enemy',power:10,damage_multiplier:null,requires_weapon:false,allowed_weapon_tags:[],cooldown_type:'turn',cooldown_value:0,cost_type:'None',cost_value:0,max_targets:1,starter:false,loadout_order:null,status_effect_slug:null,affliction_ops:[],effect_chain:[],rank_upgrades:{},duration_turns:3,guard_percent:60,ability_type:'attack'},
      ability_archetypes:{slug:'new-archetype',name:'New Archetype',description:'Reusable ability starting point.',definition:first('ability_archetypes')?.definition||{}},
      weapon_definitions:{slug:'new-weapon',name:'New Weapon',weapon_type_slug:first('weapon_types')?.slug||'sword',base_damage:10,required_rank:first('ranks')?.slug||'iron'},
      gear_definitions:{slug:'new-armor',name:'New Armor',slot:'Chest',bonuses:{Defense:1},required_rank:first('ranks')?.slug||'iron',price:100},
      consumables:{slug:'new-loot-item',name:'New Loot Item',description:'',effect:'heal',power:10},
      enemy_abilities:{enemy_slug:first('enemies')?.slug||'',ability_id:first('abilities')?.id||'',weight:1,priority:0},
      enemy_weapons:{enemy_slug:first('enemies')?.slug||'',weapon_type_slug:first('weapon_types')?.slug||''},
      orb_outcomes:{orb_slug:first('consumables',v=>v.effect==='orb')?.slug||'',essence_slug:first('essences')?.consumable_slug||'',ability_id:first('abilities')?.id||''},
      essences:{consumable_slug:first('consumables',v=>v.effect==='essence'&&!data.editor.catalogs.essences.records.some(e=>e.values.consumable_slug===v.slug))?.slug||'',active:true,powers:{}},
    };
    const values=templates[current];
    if(values){editDefinition(current,{key:{},values,revision:null},schema(),data.editor.catalogs,true);return;}
    if(sourceRows().length)open(sourceRows()[0],true);
  }
  function pairWeapon(weapon){
    const quests=data.editor.catalogs.quests.records.filter(q=>q.values.journey?.encounter_groups?.loot_tiers?.length);
    if(!quests.length){alert('No quests currently have editable loot tiers.');return;}
    const dialog=node('dialog','catalog-editor');dialog.setAttribute('aria-label','Pair weapon to quest');
    const title=node('h2','',`Pair ${weapon.values.name} to a quest`),copy=node('p','','Choose the quest and loot tier where this weapon can drop. Saving updates the quest definition in the database.');
    const fields=node('div','editor-fields'),questLabel=node('label','','Quest'),questSelect=node('select'),tierLabel=node('label','','Loot tier'),tierSelect=node('select'),weightLabel=node('label','','Drop weight'),weight=node('input');weight.type='number';weight.min='1';weight.value='1';
    quests.forEach((q,i)=>questSelect.add(new Option(q.values.name,q.values.slug,i===0,i===0)));
    function tiers(){const q=quests.find(x=>x.values.slug===questSelect.value);tierSelect.replaceChildren(...q.values.journey.encounter_groups.loot_tiers.map((t,i)=>new Option(t.name,String(i))));}
    questSelect.onchange=tiers;tiers();questLabel.append(questSelect);tierLabel.append(tierSelect);weightLabel.append(weight);fields.append(questLabel,tierLabel,weightLabel);
    const status=node('p');status.setAttribute('role','alert');const actions=node('div','editor-actions'),save=node('button','','Deploy to quest'),cancel=node('button','','Cancel');save.type=cancel.type='button';
    cancel.onclick=()=>dialog.close();save.onclick=async()=>{save.disabled=cancel.disabled=true;status.textContent='Validating quest update...';try{const quest=quests.find(x=>x.values.slug===questSelect.value),values=structuredClone(quest.values),drop={name:weapon.values.name,weapon_type_slug:weapon.values.weapon_type_slug,base_damage:weapon.values.base_damage,weight:Number(weight.value)};values.journey.encounter_groups.loot_tiers[Number(tierSelect.value)].drops.push(drop);const payload={catalog:'quests',key:quest.key,values,create:false,expected_revision:quest.revision};await api('/catalog-editor',{...payload,validate_only:true});if(!confirm(`Deploy ${weapon.values.name} to ${quest.values.name}?`)){status.textContent='Deployment cancelled.';return;}await api('/catalog-editor',payload);dialog.close();dialog.remove();await load(`Deployed ${weapon.values.name} to ${quest.values.name}.`);}catch(e){status.textContent=e.message;}finally{save.disabled=cancel.disabled=false;}};
    actions.append(save,cancel);dialog.append(title,copy,fields,status,actions);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();
  }
  function renderNav(){nav.replaceChildren();for(const s of sections){const b=node('button');b.type='button';b.setAttribute('aria-current',String(current===s.key));b.innerHTML=`<i>${icons[s.key]}</i><span>${s.label}</span>`;b.onclick=()=>{current=s.key;selected=null;search.value='';render();};nav.append(b);}}
  function renderDetail(record){const v=record.values,box=node('div','studio-detail'),head=node('div','studio-detail-head'),titles=node('div');titles.append(node('p','studio-kicker',sections.find(s=>s.key===current).singular),node('h3','',v.name||v.slug||recordLabel(current,record)));const actions=node('div','studio-actions'),edit=node('button','studio-button','Edit'),copy=node('button','studio-button secondary','Duplicate');edit.onclick=()=>open(record);copy.onclick=()=>open(record,true);copy.hidden=['enemy_abilities','enemy_weapons','orb_outcomes','essences'].includes(current);actions.append(edit,copy);if(['enemy_abilities','enemy_weapons','orb_outcomes'].includes(current))actions.append(detailAction('Remove',()=>removeAssociation(record)));head.append(titles,actions);box.append(head);
    if(current==='quests'){
      const villages=catalogRecords('villages').filter(x=>x.values.region===v.region);
      relationGroup(box,'Village / region',villages.map(x=>relationLink('villages',x,`${x.values.name} \u00b7 ${v.region}`)),'No village uses this region.');
      const slugs=[...new Set((v.journey?.stages||[]).flatMap(stage=>stage.groups||[]).flat())];
      relationGroup(box,'Encounter enemies',slugs.map(slug=>{const enemy=catalogRecords('enemies').find(x=>x.values.slug===slug);return enemy?relationLink('enemies',enemy):node('span','studio-chip',slug+' (missing)');}));
      box.append(node('h4','','Route stages'));
      for(const [index,stage] of (v.journey?.stages||[]).entries())box.append(node('p','',`${index+1}. ${stage.description} \u2014 ${(stage.groups||[]).length} possible group${stage.groups?.length===1?'':'s'}`));
      box.append(node('h4','','Loot tables'));
      const tiers=v.journey?.encounter_groups?.loot_tiers||[];
      if(!tiers.length)box.append(node('p','','No weighted loot tables configured.'));
      for(const tier of tiers){const total=(tier.drops||[]).reduce((n,d)=>n+(d.weight||1),0);box.append(node('p','',`${tier.name}: ${tier.drop_chance_percent??100}% drop chance`));const chips=node('div','studio-chips');for(const drop of tier.drops||[]){const share=total?Math.round((drop.weight||1)*1000/total)/10:0;chips.append(node('span','studio-chip',`${drop.name} \u00b7 ${share}% of drops \u00b7 weight ${drop.weight||1}`));}box.append(chips);}
    } else if(current==='enemies'){
      box.append(node('h4','','Stat ranges'));const chips=node('div','studio-chips');for(const [k,x] of Object.entries(v.stat_ranges||{}))chips.append(node('span','studio-chip',`${k}: ${x.min}\u2013${x.max}`));box.append(chips);
      const assignments=catalogRecords('enemy_abilities').filter(x=>x.values.enemy_slug===v.slug);
      relationGroup(box,'Assigned abilities',assignments.map(x=>{const ability=catalogRecords('abilities').find(a=>String(a.values.id)===String(x.values.ability_id));return relationLink('enemy_abilities',x,`${ability?.values.name||x.values.ability_id} \u00b7 weight ${x.values.weight}`);}));
      const firstAbility=catalogRecords('abilities')[0]?.values;if(firstAbility)box.append(detailAction('Assign an ability',()=>createAssociation('enemy_abilities',{enemy_slug:v.slug,ability_id:firstAbility.id,weight:1,priority:0})));
      const weapon=catalogRecords('enemy_weapons').find(x=>x.values.enemy_slug===v.slug);relationGroup(box,'Assigned weapon type',weapon?[relationLink('enemy_weapons',weapon,weapon.values.weapon_type_slug)]:[]);const firstType=catalogRecords('weapon_types')[0]?.values;if(!weapon&&firstType)box.append(detailAction('Assign a weapon type',()=>createAssociation('enemy_weapons',{enemy_slug:v.slug,weapon_type_slug:firstType.slug})));
      const quests=catalogRecords('quests').filter(q=>(q.values.journey?.stages||[]).some(s=>(s.groups||[]).flat().includes(v.slug)));
      relationGroup(box,'Used by quests',quests.map(q=>relationLink('quests',q)));
    } else if(current==='enemy_abilities'){
      const enemy=catalogRecords('enemies').find(x=>x.values.slug===v.enemy_slug),ability=catalogRecords('abilities').find(x=>String(x.values.id)===String(v.ability_id));
      relationGroup(box,'Association',[enemy?relationLink('enemies',enemy):node('span','studio-chip',v.enemy_slug),ability?relationLink('abilities',ability):node('span','studio-chip',v.ability_id)]);
      box.append(node('p','',`Selection weight ${v.weight}; priority ${v.priority}.`));
    } else if(current==='enemy_weapons'){
      const enemy=catalogRecords('enemies').find(x=>x.values.slug===v.enemy_slug),type=catalogRecords('weapon_types').find(x=>x.values.slug===v.weapon_type_slug);relationGroup(box,'Association',[enemy?relationLink('enemies',enemy):node('span','studio-chip',v.enemy_slug),type?relationLink('weapon_types',type):node('span','studio-chip',v.weapon_type_slug)]);
    } else if(current==='abilities'){
      const archetype=catalogRecords('ability_archetypes').find(x=>x.values.slug===v.archetype_slug);
      relationGroup(box,'Starting archetype',archetype?[relationLink('ability_archetypes',archetype)]:[],'Custom definition');
      box.append(node('h4','','Effect chain'),node('p','',`Primary: ${v.effect_type} · power ${v.power} · ${v.target_type}`));
      for(const [i,step] of (v.effect_chain||[]).entries())box.append(node('p','',`${i+1}. ${step.effect} → ${step.recipient} · ${step.when||'on_damage'} · ${step.effect==='modifier'?`${step.stat} ${step.modifier>0?'+':''}${step.modifier}${step.operation==='percent'?'%':''} for ${step.duration} rounds`:`${step.value}${step.source==='fixed'?'':'%'} of ${step.source}${step.split?' (split)':''}`}`));
      box.append(node('h4','','Rank upgrades'),node('p','',Object.keys(v.rank_upgrades||{}).join(', ')||'No rank overrides yet.'));
      box.append(detailAction('Save as archetype',()=>{const keys=['effect_type','target_type','power','damage_multiplier','requires_weapon','allowed_weapon_tags','cooldown_type','cooldown_value','max_targets','duration_turns','guard_percent','effect_chain','rank_upgrades','ability_type','status_effect_slug','affliction_ops'];editDefinition('ability_archetypes',{key:{},revision:null,values:{slug:v.slug+'-archetype',name:v.name+' archetype',description:v.description,definition:Object.fromEntries(keys.map(k=>[k,v[k]]))}},data.editor.catalogs.ability_archetypes,data.editor.catalogs,true);}));
      const enemies=catalogRecords('enemy_abilities').filter(x=>String(x.values.ability_id)===String(v.id));
      relationGroup(box,'Enemies using this ability',enemies.map(x=>relationLink('enemy_abilities',x,x.values.enemy_slug)));
      const recipes=catalogRecords('orb_outcomes').filter(x=>String(x.values.ability_id)===String(v.id));
      relationGroup(box,'Essence recipes teaching it',recipes.map(x=>relationLink('orb_outcomes',x,`${x.values.essence_slug} + ${x.values.orb_slug}`)));
      const firstEnemy=catalogRecords('enemies')[0]?.values;if(firstEnemy)box.append(detailAction('Assign to an enemy',()=>createAssociation('enemy_abilities',{enemy_slug:firstEnemy.slug,ability_id:v.id,weight:1,priority:0})));
      box.append(node('h4','','Definition data'),node('pre','studio-json',JSON.stringify(v,null,2)));
    } else if(current==='ability_archetypes'){
      box.append(node('p','',v.description),node('h4','','Saved starting values'),node('pre','studio-json',JSON.stringify(v.definition,null,2)));
      relationGroup(box,'Abilities created from this archetype',catalogRecords('abilities').filter(x=>x.values.archetype_slug===v.slug).map(x=>relationLink('abilities',x)));
      box.append(detailAction('Create ability from archetype',()=>{const base=catalogRecords('abilities')[0]?.values;if(!base)return;editDefinition('abilities',{key:{},revision:null,values:{...base,status_effect_slug:null,affliction_ops:[],...v.definition,id:'',slug:v.slug+'-ability',name:v.name+' ability',description:v.description,archetype_slug:v.slug,starter:false,loadout_order:null,cost_type:'None',cost_value:0}},data.editor.catalogs.abilities,data.editor.catalogs,true);}));
    } else if(current==='afflictions'){
      const abilities=catalogRecords('abilities').filter(x=>x.values.status_effect_slug===v.slug||(x.values.affliction_ops||[]).some(op=>op.affliction===v.slug));relationGroup(box,'Used by abilities',abilities.map(x=>relationLink('abilities',x)));const types=catalogRecords('entity_types').filter(x=>v.slug in (x.values.status_resistances||{}));relationGroup(box,'Enemy type resistances',types.map(x=>relationLink('entity_types',x,`${x.values.slug} \u00b7 ${x.values.status_resistances[v.slug]}%`)));
    } else if(current==='entity_types'){
      const enemies=catalogRecords('enemies').filter(x=>x.values.enemy_type===v.slug);relationGroup(box,'Enemies of this type',enemies.map(x=>relationLink('enemies',x)));box.append(node('h4','','Affliction resistances'),node('pre','studio-json',JSON.stringify(v.status_resistances||{},null,2)));
    } else if(current==='essences'){
      const recipes=catalogRecords('orb_outcomes').filter(x=>x.values.essence_slug===v.consumable_slug);
      relationGroup(box,'Orb and ability combinations',recipes.map(x=>relationLink('orb_outcomes',x,`${x.values.orb_slug} \u2192 ${abilityName(x.values.ability_id)}`)));
      const orb=catalogRecords('consumables').find(x=>x.values.effect==='orb')?.values,ability=catalogRecords('abilities')[0]?.values;if(orb&&ability)box.append(detailAction('Add ability recipe',()=>createAssociation('orb_outcomes',{orb_slug:orb.slug,essence_slug:v.consumable_slug,ability_id:ability.id})));
      const quests=catalogRecords('quests').filter(q=>questDrops(q).some(x=>x.drop.consumable_slug===v.consumable_slug));
      relationGroup(box,'Available from quests',quests.map(q=>relationLink('quests',q)));
      box.append(node('h4','','Powers'),node('pre','studio-json',JSON.stringify(v.powers||{},null,2)));
    } else if(current==='orb_outcomes'){
      const essence=catalogRecords('essences').find(x=>x.values.consumable_slug===v.essence_slug),ability=catalogRecords('abilities').find(x=>String(x.values.id)===String(v.ability_id)),orb=catalogRecords('consumables').find(x=>x.values.slug===v.orb_slug);
      relationGroup(box,'Combination',[orb?relationLink('consumables',orb):node('span','studio-chip',v.orb_slug),essence?relationLink('essences',essence):node('span','studio-chip',v.essence_slug),ability?relationLink('abilities',ability):node('span','studio-chip',v.ability_id)]);
    } else if(current==='consumables'){
      const essence=catalogRecords('essences').find(x=>x.values.consumable_slug===v.slug);
      if(essence)relationGroup(box,'Essence definition',[relationLink('essences',essence)]);
      else if(v.effect==='essence')box.append(detailAction('Create essence definition',()=>createAssociation('essences',{consumable_slug:v.slug,active:true,powers:{}})));
      const quests=catalogRecords('quests').filter(q=>questDrops(q).some(x=>x.drop.consumable_slug===v.slug));relationGroup(box,'Available from quests',quests.map(q=>relationLink('quests',q)));
    } else if(current==='weapon_definitions'){
      box.append(node('h4','','Weapon blueprint'),node('p','',`${v.weapon_type_slug} \u00b7 ${v.base_damage} base damage \u00b7 ${v.required_rank} rank`));const quests=catalogRecords('quests').filter(q=>questDrops(q).some(x=>x.drop.name===v.name&&x.drop.weapon_type_slug===v.weapon_type_slug&&x.drop.base_damage===v.base_damage));relationGroup(box,'Available from quests',quests.map(q=>relationLink('quests',q)));const pair=node('button','studio-button','Add to quest loot');pair.disabled=!data.editor?.can_edit;pair.onclick=()=>pairWeapon(record);box.append(pair);
    } else if(current==='weapon_types'){
      const weapons=catalogRecords('weapon_definitions').filter(x=>x.values.weapon_type_slug===v.slug),enemies=catalogRecords('enemy_weapons').filter(x=>x.values.weapon_type_slug===v.slug),quests=catalogRecords('quests').filter(q=>questDrops(q).some(x=>x.drop.weapon_type_slug===v.slug));relationGroup(box,'Weapon blueprints',weapons.map(x=>relationLink('weapon_definitions',x)));relationGroup(box,'Enemy assignments',enemies.map(x=>relationLink('enemy_weapons',x,x.values.enemy_slug)));relationGroup(box,'Quest loot tables',quests.map(x=>relationLink('quests',x)));
    } else if(current==='ranks'){
      const quests=catalogRecords('quests').filter(x=>x.values.journey?.required_rank===v.slug),weapons=catalogRecords('weapon_definitions').filter(x=>x.values.required_rank===v.slug),gear=catalogRecords('gear_definitions').filter(x=>x.values.required_rank===v.slug);relationGroup(box,'Required by quests',quests.map(x=>relationLink('quests',x)));relationGroup(box,'Required by weapons',weapons.map(x=>relationLink('weapon_definitions',x)));relationGroup(box,'Required by armor',gear.map(x=>relationLink('gear_definitions',x)));
    } else if(current==='rest_policies'){
      const quests=catalogRecords('quests').filter(x=>x.values.journey?.camp_rest===v.slug);relationGroup(box,'Used by quests',quests.map(x=>relationLink('quests',x)));box.append(node('h4','','Recovery settings'),node('pre','studio-json',JSON.stringify(v.settings||{},null,2)));
    } else if(current==='villages'){
      const quests=catalogRecords('quests').filter(x=>x.values.region===v.region),shops=catalogRecords('shops').filter(x=>x.values.village_slug===v.slug);relationGroup(box,'Associated quests',quests.map(x=>relationLink('quests',x)));relationGroup(box,'Village shops',shops.map(x=>relationLink('shops',x)));
    } else if(current==='shops'){
      const village=catalogRecords('villages').find(x=>x.values.slug===v.village_slug),tables=catalogRecords('shop_tables').filter(x=>x.values.shop_slug===v.slug);relationGroup(box,'Village',village?[relationLink('villages',village)]:[]);relationGroup(box,'Stock tables',tables.map(x=>relationLink('shop_tables',x)));
    } else if(current==='shop_tables'){
      const shop=catalogRecords('shops').find(x=>x.values.slug===v.shop_slug);relationGroup(box,'Shop',shop?[relationLink('shops',shop)]:[]);box.append(node('h4','','Stock'),node('pre','studio-json',JSON.stringify(v.items||[],null,2)));
    } else box.append(node('h4','','Definition data'),node('pre','studio-json',JSON.stringify(v.bonuses||v,null,2)));
    return box;}
  function render(){const oldList=content.querySelector('.studio-list');if(oldList&&renderedSection)libraryScroll[renderedSection]=oldList.scrollTop;renderNav();content.replaceChildren();const section=sections.find(s=>s.key===current),heading=node('div','studio-heading'),title=node('div');title.append(node('p','studio-kicker','Content library'),node('h2','',section.label),node('p','',section.copy));const actions=node('div','studio-actions'),create=node('button','studio-button',`+ New ${section.singular}`);create.onclick=createDefinition;actions.append(create);heading.append(title,actions);content.append(heading);if(!data){renderedSection=current;content.append(node('div','studio-empty','Load the development catalog to begin.'));return;}if(!data.editor?.can_edit)content.append(node('p','studio-warning','Catalog editing is disabled for this account. A developer account is required.'));
    const counts=['quests','enemies','weapon_definitions','gear_definitions'].map(k=>k===current?sourceRows().length:(data.editor?.catalogs?.[k]?.records.length||0)),stats=node('div','studio-stats');[['Quests',counts[0]],['Enemies',counts[1]],['Weapons',counts[2]],['Armor',counts[3]]].forEach(([label,value])=>{const x=node('div','studio-stat');x.innerHTML=`<small>${label}</small><strong>${value}</strong><span>live</span>`;stats.append(x);});content.append(stats);
    const list=node('div','studio-panel'),listHead=node('div','studio-panel-head'),visible=rows();listHead.append(node('b','',`${section.label} library`),node('span','studio-count',`${visible.length} definitions`));list.append(listHead);const body=node('div','studio-list');list.append(body);if(!visible.length)body.append(node('div','studio-empty','No matching definitions.'));selected=visible.find(r=>JSON.stringify(r.key)===JSON.stringify(selected?.key))||visible[0]||null;
    for(const record of visible){const v=record.values,row=node('div','studio-row'+(record===selected?' selected':''));row.tabIndex=0;row.setAttribute('role','button');row.onclick=()=>{selected=record;render();};const identity=node('div');identity.append(node('h3','',v.name||v.slug||recordLabel(current,record)),node('small','',v.slug||Object.values(record.key).join(' + ')));row.append(identity,node('span','studio-tag',category(record)),node('p','',summary(record)));const more=node('button','','\u00b7\u00b7\u00b7');more.title=record.readonly?'Read-only preview':'Edit definition';more.disabled=Boolean(record.readonly);more.onclick=e=>{e.stopPropagation();open(record);};row.append(more);body.append(row);}const browser=node('div','studio-browser');browser.append(list,selected?renderDetail(selected):node('div','studio-detail studio-empty','Select an item to inspect it.'));content.append(browser);renderedSection=current;body.scrollTop=libraryScroll[current]||0;}
  async function load(message){refresh.disabled=true;try{data=await api('/abilities?inspect=true');render();sideNote.querySelector('div:last-child').textContent=message||`Synced ${new Date(data.generated_at).toLocaleTimeString()}`;}catch(e){data=null;render();content.prepend(node('p','studio-warning','Unable to load content: '+e.message));}finally{refresh.disabled=false;}}
  search.oninput=()=>{selected=null;render();};refresh.onclick=()=>load();exportButton.onclick=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='mosswood-world-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};root.refresh=()=>load();load();return root;
};
